spring:
  datasource:
    driverClassName: org.h2.Driver
    hikari:
      maximum-pool-size: 25
    platform: h2
    url: jdbc:h2:file:./db_dev/thespringboot
    username: dev
    password: dev
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: UTC-3
        show_sql: true // em DEV
        type: trace
        use_sql_comments: false
  profiles:
    active: dev
